version: '3.8'

services:
  app:
    container_name: app
    image: app
    restart: always # Try to restart of crash
    build:
      context: .
    env_file:
      - ./.env
    ports:
      - 5000:5000
    depends_on: # Do not start app until postgres and redis starts (due to dependency)
      - postgres
      - redis
    environment:
      - FLASK_ENV=development # For hot reload
    volumes: # Sync host and container
      - .:/app

  postgres:
    image: postgres:12
    container_name: postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6.2.5
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

  adminer: # PGAdmin like tool
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080


volumes:
  pgdata:
  redisdata:
